name: Trigger intellifactorylabs.com deployment
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch for intellifactory.github.io
        run: |
          curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/intellifactory/intellifactory.github.io/dispatches --data '{"event_type": "build_application"}'
